version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      # Disable xpack security (for development purposes)
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    volumes:
      - ./data:/usr/share/elasticsearch/data
  app:
    image: python:3.10.2-slim-bullseye
    container_name: app
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python data_loader.py"
    depends_on:
      - elasticsearch
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
